phase1:
	./hex2raw < touch1.txt | ./ctarget -q
phase2:
	./hex2raw < touch2.txt | ./ctarget -q
phase3:
	./hex2raw < touch3.txt | ./ctarget -q
phase4:
	./hex2raw < touch4.txt | ./rtarget -q
phase5:
	./hex2raw < touch5.txt | ./rtarget -q